name: Increment Semantic Version
description: Bump a given semantic version by a release type ( major | minor | patch ) and add a possible postfix ( alpha | beta | rc )
author: Christian Dräger
branding:
  icon: 'tag'
  color: 'purple'
inputs:
  current-version:
    description: 'The current semantic version you want to increment'
    required: true
  version-fragment:
    description: 'The versions fragment you want to increment. possible options are [ major | feature| minor | bug | patch | hotfix | alpha | beta | rc ]'
    required: true
outputs:
  next-version:
    description: 'The incremented version'
    value: ${{ steps.bump-version.outputs.next-version }}
runs:
  using: "composite"
  steps:
    - name: Run entrypoint.sh
      id: bump-version
      shell: bash
      run: |
        "$GITHUB_ACTION_PATH"/entrypoint.sh "${{ inputs.current-version }}" "${{ inputs.version-fragment }}"
